version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8032:80"
    volumes:
      - ../website:/website
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - biscuit-network

  php:
    image: php:fpm
    volumes:
      - ../website:/website
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - biscuit-network

networks:
  biscuit-network:
    driver: bridge
